I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 387, in script
    P "You know what, I'm also getting kinda bored.."
Exception: Sayer 'P' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 387, in script
    P "You know what, I'm also getting kinda bored.."
  File "D:\apps\renpy-8.3.6-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "D:\apps\renpy-8.3.6-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\apps\renpy-8.3.6-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'P' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.6.25022803
Ye Bear Adventures 1.0
Tue Mar  4 23:50:11 2025
